# Generated by Django 5.0.4 on 2024-07-15 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('post', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('numStageActf', models.CharField(max_length=50, null=True)),
                ('numStagePassif', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('ecole', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('niv', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('Suject', models.TextField(blank=True, null=True)),
                ('Source', models.TextField(blank=True, null=True)),
                ('statusStage', models.CharField(choices=[('Fin', 'Fin'), ('PasEncore', 'PasEncore'), ('Encours', 'Encours')], default='PasEncore', max_length=50)),
                ('type', models.CharField(choices=[('Application', 'Application'), ('Observation', 'Observation'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50)),
                ('encadrent', models.ManyToManyField(to='site1.encadrent')),
                ('stagiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site1.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDocumment', models.CharField(choices=[('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('CV', 'CV'), ('LettreMotivation', 'LettreMotivation'), ('Assurece', 'Assurece')], default='Observation', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('stagiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site1.stagiaire')),
            ],
        ),
    ]
