# Generated by Django 5.0.4 on 2024-07-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Assurece', 'Assurece'), ('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('CV', 'CV'), ('LettreMotivation', 'LettreMotivation')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Fin', 'Fin'), ('Encours', 'Encours'), ('PasEncore', 'PasEncore')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Observation', 'Observation'), ('Application', 'Application'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50),
        ),
    ]
