# Generated by Django 5.0.4 on 2024-07-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_alter_document_typedocumment_alter_stage_statusstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Rapport', 'Rapport'), ('Assurece', 'Assurece'), ('CV', 'CV'), ('Convocation', 'Convocation'), ('LettreMotivation', 'LettreMotivation')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Observation', 'Observation'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50),
        ),
    ]
