# Generated by Django 5.0.4 on 2024-07-15 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_stage_commentaire_alter_document_typedocumment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Convocation', 'Convocation'), ('LettreMotivation', 'LettreMotivation'), ('CV', 'CV'), ('Rapport', 'Rapport'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='encadrent',
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Encours', 'Encours'), ('Fin', 'Fin')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Embouchement', 'Embouchement'), ('Observation', 'Observation'), ('Application', 'Application')], default='Observation', max_length=50),
        ),
        migrations.AddField(
            model_name='stage',
            name='encadrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site1.encadrent'),
        ),
    ]
