# Generated by Django 5.0.4 on 2024-07-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_alter_document_typedocumment_remove_stage_encadrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('LettreMotivation', 'LettreMotivation'), ('Convocation', 'Convocation'), ('CV', 'CV'), ('Rapport', 'Rapport'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Fin', 'Fin'), ('Encours', 'Encours')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Embouchement', 'Embouchement'), ('Application', 'Application'), ('Observation', 'Observation')], default='Observation', max_length=50),
        ),
    ]
