# Generated by Django 5.0.4 on 2024-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_stage_nom_alter_document_typedocumment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('CV', 'CV'), ('Assurece', 'Assurece'), ('LettreMotivation', 'LettreMotivation')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Fin', 'Fin'), ('PasEncore', 'PasEncore'), ('Encours', 'Encours')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Embouchement', 'Embouchement'), ('Observation', 'Observation')], default='Observation', max_length=50),
        ),
    ]
