# Generated by Django 5.0.4 on 2024-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_alter_document_typedocumment_alter_stage_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Rapport', 'Rapport'), ('LettreMotivation', 'LettreMotivation'), ('Assurece', 'Assurece'), ('CV', 'CV'), ('Convocation', 'Convocation')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Encours', 'Encours'), ('PasEncore', 'PasEncore'), ('Fin', 'Fin')], default='PasEncore', max_length=50),
        ),
    ]
