# Generated by Django 5.0.4 on 2024-07-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_alter_document_typedocumment_alter_stage_statusstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('LettreMotivation', 'LettreMotivation'), ('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('CV', 'CV'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='encadrent',
            name='image',
            field=models.ImageField(blank=True, default='png.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Fin', 'Fin'), ('Encours', 'Encours')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='image',
            field=models.ImageField(blank=True, default='png.png', null=True, upload_to='profile/'),
        ),
    ]
