# Generated by Django 5.0.4 on 2024-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0008_alter_document_typedocumment_alter_encadrent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrent',
            name='image',
            field=models.ImageField(default='png.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Fin', 'Fin'), ('PasEncore', 'PasEncore'), ('Encours', 'Encours')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Observation', 'Observation'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='image',
            field=models.ImageField(default='png.png', null=True, upload_to='profile/'),
        ),
    ]
