# Generated by Django 5.0.4 on 2024-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0009_alter_encadrent_image_alter_stage_statusstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('CV', 'CV'), ('LettreMotivation', 'LettreMotivation'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Fin', 'Fin'), ('Encours', 'Encours'), ('PasEncore', 'PasEncore')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Embouchement', 'Embouchement'), ('Observation', 'Observation'), ('Application', 'Application')], default='Observation', max_length=50),
        ),
    ]
