# Generated by Django 5.0.4 on 2024-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0010_alter_document_typedocumment_alter_stage_statusstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('LettreMotivation', 'LettreMotivation'), ('Convocation', 'Convocation'), ('CV', 'CV'), ('Rapport', 'Rapport'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Encours', 'Encours'), ('PasEncore', 'PasEncore'), ('Fin', 'Fin')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Observation', 'Observation'), ('Application', 'Application'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
