# Generated by Django 5.0.4 on 2024-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0011_alter_document_typedocumment_alter_stage_statusstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Assurece', 'Assurece'), ('CV', 'CV'), ('Convocation', 'Convocation'), ('Rapport', 'Rapport'), ('LettreMotivation', 'LettreMotivation')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Encours', 'Encours'), ('Fin', 'Fin')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Observation', 'Observation'), ('Embouchement', 'Embouchement')], default='Observation', max_length=50),
        ),
    ]
