# Generated by Django 5.0.4 on 2024-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0012_alter_document_typedocumment_alter_stage_statusstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('LettreMotivation', 'LettreMotivation'), ('Rapport', 'Rapport'), ('Convocation', 'Convocation'), ('CV', 'CV'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('Fin', 'Fin'), ('Encours', 'Encours'), ('PasEncore', 'PasEncore')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Embouchement', 'Embouchement'), ('Observation', 'Observation'), ('Application', 'Application')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='image',
            field=models.ImageField(default='png.png', null=True, upload_to='profile/'),
        ),
    ]
