# Generated by Django 5.0.4 on 2024-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0014_alter_document_typedocumment_alter_encadrent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrent',
            name='numStageActf',
        ),
        migrations.RemoveField(
            model_name='encadrent',
            name='numStagePassif',
        ),
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('Convocation', 'Convocation'), ('CV', 'CV'), ('Rapport', 'Rapport'), ('LettreMotivation', 'LettreMotivation'), ('Assurece', 'Assurece')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Fin', 'Fin'), ('Encours', 'Encours')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Embouchement', 'Embouchement'), ('Application', 'Application'), ('Observation', 'Observation')], default='Observation', max_length=50),
        ),
    ]
