# Generated by Django 5.0.4 on 2024-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0015_remove_encadrent_numstageactf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typeDocumment',
            field=models.CharField(choices=[('LettreMotivation', 'LettreMotivation'), ('CV', 'CV'), ('Convocation', 'Convocation'), ('Assurece', 'Assurece'), ('Rapport', 'Rapport')], default='Observation', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statusStage',
            field=models.CharField(choices=[('PasEncore', 'PasEncore'), ('Encours', 'Encours'), ('Fin', 'Fin')], default='PasEncore', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Observation', 'Observation'), ('Embouchement', 'Embouchement'), ('Application', 'Application')], default='Observation', max_length=50),
        ),
    ]
